db:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: whaler
    MYSQL_USER: whaler
    MYSQL_PASSWORD: admin

api:
  build: ./whaler-api
  command: /bin/bash -c "ruby bin/setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - ./whaler-api:/whaler-api
    - /var/run/docker.sock:/var/run/docker.sock
  ports:
    - "3000:3000"
  links:
    - db
    - redis
  environment:
    DOCKER_CERT_PATH: /home/.docker
    RAILS_ENV: development

ui:
  build: ./whaler-ui
  command: /bin/bash -c "ruby bin/setup && bundle exec rails s -p 80 -b '0.0.0.0'"
  volumes:
    - ./whaler-ui:/whaler-ui
    - .git:/.git
  ports:
    - "80:80"
  links:
    - db
  environment:
    RAILS_ENV: development

monitor:
  build: ./whaler-api
  volumes:
    - ./whaler-api:/whaler-api
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - redis
  command: rake monit:event:start DEBUG=y

# Syslog UDP server to trigger containers logs to ui with WebSocket
logs:
  build: ./whaler-logs
  links:
    - redis
  volumes:
    - ./whaler-logs:/usr/src/app
  ports:
    - "3002:3002/udp"

logspout:
  image: gliderlabs/logspout
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  links:
    - logs
  command: syslog://logs:3002

redis:
  image: redis:latest
  ports:
    - "6379:6379"
